@startuml
left to right direction
skinparam actorStyle awesome
skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkSlateGray
    ArrowColor Black
    ActorBorderColor black
    ActorFontName Courier
    ActorBackgroundColor<< Human >> Gold
}
actor  "Guest User" as Anonymous #Blue
actor  "Admin" as Admin #Red
actor  "Customer" as User #Green

rectangle "Corso System"{
 rectangle "LLUC6 : View services Use case" as Services #line.dashed {
    usecase "6.1 : View service section" as UC17
    usecase "6.2 : Modify service section" as UC18
    usecase "6.3 : View service reports" as UC19

    Anonymous -[#blue]-> UC17 
    Admin -[#red]-> UC18
    Admin -[#red]-> UC19

    UC18 -[dashed]> UC17 : <<includes>>
    User --|> Anonymous
    Admin --|> User
  }
}
@endpuml
