@startuml

left to right direction
skinparam actorStyle awesome
skinparam usecase {
    BackgroundColor DarkSeaGreen
    BorderColor DarkSlateGray
    ArrowColor Black
    ActorBorderColor black
    ActorFontName Courier
    ActorBackgroundColor<< Human >> Gold
}

actor  "Guest User" as anonymous #Blue
actor  "Customer" as User #Green
actor  "Admin User" as Admin #Red

rectangle "System" {
  rectangle "FAQ Subsystem" as FAQ {
    usecase "2.1 : View all FAQ" as UC1
    usecase "2.2 : Modify FAQ section" as UC2
  }
}
anonymous -[#Blue]->  UC1
User --|> anonymous
Admin --|> User
Admin -[#Red]-> UC2


@enduml