@startuml
title Delete FAQ of FAQ

actor Admin

participant "<<View>>\nDashboard" as Dashboard
participant "<<View>>\nViewSpecificFaq" as CurrentFAQ
participant "<<Controller>>\nFAQController" as FAQController
participant "<<Service>>\nFAQService" as FAQService
participant FAQ as "faq: FAQ"
participant "<<repository>>\nFAQRepository" as FAQRepository
participant "Database" as Db

ref over Dashboard, CurrentFAQ, FAQController, FAQService, FAQRepository, Db

    ViewFaqs

end


opt
Admin -> Dashboard: ViewSpecificFaq(faqId: String)
activate Dashboard

Dashboard -> CurrentFAQ: render()
activate CurrentFAQ

CurrentFAQ -> FAQController: DELETE api/v1/corso/faqs/{faqId}
activate FAQController

FAQController -> FAQService: deleteFAQByFaqId(faqId: String)
activate FAQService

FAQService -> FAQRepository: getFAQBYFAQId_FAQId(faqId: String)

activate FAQRepository

FAQRepository -> Db: SELECT * FROM faq WHERE faqId = faqId

activate Db

Db --> FAQ : faq: FAQ
deactivate Db

activate FAQ
FAQ --> FAQRepository: faq

FAQRepository --> FAQService: faq

FAQService -> FAQRepository: delete(faq)

FAQRepository -> Db: DELETE FROM faq WHERE faqId = faqId
deactivate FAQ
activate Db

Db --> FAQRepository: void
deactivate Db

FAQRepository --> FAQService: void
deactivate FAQRepository

FAQService --> FAQController: void
deactivate FAQService

FAQController --> CurrentFAQ: void
deactivate FAQController
end
@enduml