@startuml

title View FAQ Section Use Case Sequence Diagram

actor User

participant HomePage as "<<View>>\nHomePage"

participant Dashboard as "<<View>>\nDashboard"

participant ManageFaqPage as "<<View>>\nManageFaqPage"

participant ViewAllFaqPage as "<<View>>\nViewAllFaqPage"

participant FaqController as "<<Controller>>\nFaqController"

participant FaqService as "<<Service>>\nFaqService"

participant allFaq as "all:List<Faq>"

participant FaqRepository as "<<Repository>>\nFaqRepository"

participant allResponse as "allResponse:List<FaqResponse>"

participant Database as "<<Database>>\nDatabase"

participant FaqResponseMapper as "<<Mapper>>\nFaqResponseMapper"

ref over User, HomePage, ViewAllFaqPage, FaqController, FaqService, allFaq, FaqRepository, allResponse, Database, FaqResponseMapper
ViewPinnedFaqs
end ref

opt

alt User is Admin

User -> Dashboard: viewAllFaq()
activate Dashboard

Dashboard -> ManageFaqPage: render()

activate ManageFaqPage

ManageFaqPage -> FaqController: GET /api/v1/corso/faq HTTP/1.1



else User is Customer
User -> HomePage: viewAllFaq()
activate HomePage

HomePage -> ViewAllFaqPage: render()

activate ViewAllFaqPage

ViewAllFaqPage -> FaqController: GET /api/v1/corso/faq HTTP/1.1

end


activate FaqController

FaqController -> FaqService: getAllFaq()

activate FaqService

FaqService -> FaqRepository: findAll()

activate FaqRepository

FaqRepository -> Database: SELECT * FROM faq

activate Database

Database --> FaqRepository: List<Faq>

deactivate Database

FaqRepository --> allFaq: List<Faq>

activate allFaq

allFaq --> FaqService: all:List<Faq>

deactivate FaqRepository

FaqService -> FaqResponseMapper: mapToResponse(all)

deactivate allFaq

activate FaqResponseMapper

FaqResponseMapper --> allResponse: List<FaqResponse>

activate allResponse

allResponse --> FaqService: allResponse:List<FaqResponse>


deactivate FaqResponseMapper

FaqService --> FaqController: allResponse:List<FaqResponse>

deactivate FaqService

alt User is Admin

FaqController -> ManageFaqPage: render(allResponse)



else User is Customer

FaqController -> ViewAllFaqPage: render(allResponse)

end


deactivate allResponse

deactivate FaqController

deactivate ViewAllFaqPage





end opt


@endpuml
