@startuml

title Login State Diagram
hide empty description

[*] --> CredentialsEntered

CredentialsEntered --> SucessfullLogin : [Correct Credentials]
CredentialsEntered --> IncorrectLogin : [Incorrect Credentials]
IncorrectLogin --> CredentialsEntered : [Try Again]
IncorrectLogin --> NotLoggedIn : [Cancel]
NotLoggedIn --> [*]
SucessfullLogin --> [*] 


@endpuml